### ISSUE TITLE
Rename text domain

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/client-dash-pro#10]
I think text domains are supposed to match the main file name, though I also think it is not a strict rule. Current text domain is `clientdash-pro`. Elsewhere we are going with `client-dash-pro` which I like better. Not a big deal, just thought I'd bring it up.

**Comment by brashrebel** [comment]
Actually both those text domains are used throughout. So we need to pick one and get the rest to match.

**Comment by joelworsham** [comment]
Fixed, set to `client-dash-pro`
