### ISSUE TITLE
Error on Activation

### ISSUE THREAD

**Issue by d4mation** [realbigplugins/client-dash-pro#12]
I'm going to see if I can get some more information for you.

Note: This is apparently 1 commit behind master, but that just changed some strings. It would have no bearing on this Error.

![image](https://cloud.githubusercontent.com/assets/7770631/23667639/8695e568-032c-11e7-8cc8-be5835f7e83c.png)

**Comment by d4mation** [comment]
While it reads "License Active", looking at Slack it didn't trigger EDD Slack's "License Activated" notification.

Maybe it is causing a PHP error somewhere?

**Comment by d4mation** [comment]
Deactivating and reactivating does not produce the same error.

**Comment by d4mation** [comment]
Can't seem to reproduce this 🤔 

Deleted the License Key from the Database manually and reactivated it and the error did not appear.

**Comment by d4mation** [comment]
Looking at the code it doesn't even make sense how this could have happened.

You've got a function called `get_license_error_message()` which uses the error code from EDD to determine which error message to show. In this case, it hits the Default case.

However, it also shows the "Success" message. If the success message is shown, it shouldn't even be calling `get_license_error_message()`.

Unless both conditions were somehow met between the page refresh so _both_ Settings Errors got added, I have no idea how this happened.

**Comment by d4mation** [comment]
I would close this out as `invalid`, but even without the error there it still doesn't trigger the EDD Slack License Activation notification. This makes me think something's up since it works for all of our other plugins.

**Comment by joelworsham** [comment]
So what's the current issue? I'm getting the success notification:

~[](http://d.pr/i/Wxm6+)

**Comment by d4mation** [comment]
I'm not really sure. I haven't been able to reproduce it no matter how hard I try.

The only thing I know for certain is that the License Activation Notification for EDD Slack isn't going out. I haven't been able to test to see if it is either:

1. Caused by this plugin somehow? Doesn't seem likely as it _is_ activating
2. A problem with EDD Slack. It seems like we haven't gotten _any_ License Key Activation Notifications since Feb 11th. Maybe Software Licensing Updated and broke something?

**Comment by d4mation** [comment]
Can't reproduce. Other problems extend to other Plugin Activations as well.
