### ISSUE TITLE
500 Error if CD Free is not active

### ISSUE THREAD

**Issue by d4mation** [realbigplugins/client-dash-pro#20]
Just had this Issue and for some reason editing the file name via SFTP to force disable wasn't working so I had to edit `active_plugins` to achieve the desired result :(

**Comment by d4mation** [comment]
However, as a realated note, this is a super helpful tool: 

http://sciactive.com/phpserialeditor.php

**Comment by d4mation** [comment]
Although, just realized the version of Pro was _super_ old. This probably isn't an issue anymore. Feel free to close if so. This is on a Live site so I'd rather not play around with intentionally trying to trigger a 500 😬

**Comment by joelworsham** [comment]
Schnikees. Still bad, but if it's an old version... then oh well!

**Comment by BigActual** [comment]
Is this still an open issue?

**Comment by d4mation** [comment]
This is no longer a problem, and may not have been a problem when I opened the issue as far as the latest versions at the time were concerned. I think that in this case, they may had been running an out-of-date version.
